esphome:
  name: luz
  friendly_name: luz

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://rbaron/esphome@cypd3177
    components: [cypd3177]

# Enable logging
logger:
  level: VERBOSE
  logs:
    ledc.output: WARN
    light: WARN
    api: WARN
    api.connection: WARN
    logger: WARN
    ota: WARN
    wifi: WARN
    i2c.arduino: WARN
    app: WARN

# Enable Home Assistant API
api:
  encryption:
    key: !secret homeassistant_enc_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  ap:
    ssid: "Luz Fallback Hotspot"
    password: !secret fallback_ap_pass

captive_portal:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True
  id: i2c_bus

cypd3177:
  interrupt_pin: GPIO23
  voltage: 9000 mV
  current: 1000 mA

light:
  - platform: monochromatic
    name: Luz Channel 1
    id: luz_channel1
    output: channel1
  - platform: monochromatic
    name: Luz Channel 2
    id: luz_channel2
    output: channel2
  - platform: monochromatic
    name: Luz Built-in LED
    id: luz_built_in_led
    output: built_in_led

output:
  - platform: ledc
    id: built_in_led
    pin: GPIO27
  - platform: ledc
    id: channel1
    pin: GPIO18
  - platform: ledc
    id: channel2
    pin: GPIO4
